const {Client}=require('pg');
const express= require('express');
const dotenv=require('dotenv');
dotenv.config();
const userRouters = require('./routers/userrouter.js');
const todoRouters = require('./routers/todorouter.js');
const app=express();
app.use(express.json());
app.use('/user',userRouters);
app.use('/',todoRouters);
app.listen(process.env.port1,()=>console.log(`server is running ${process.env.port1}`));